runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: MySQLdb
  version: "latest"

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]

env_variables:
    CLOUDSQL_CONNECTION_NAME: nudistrobot:us-central1:shellbot-v1
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: LEKonmow6Mehrj9w
    PROJECT_ID: nudistrobot
    LOCATION_ID: us-central1'
    QUEUE_ID: message-count-cache-queue
